//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  attorney: Attorney;
  attorneyConnection: AttorneyConnection;
  blog: Blog;
  blogConnection: BlogConnection;
  career: Career;
  careerConnection: CareerConnection;
  practice: Practice;
  practiceConnection: PracticeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAttorneyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAttorneyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AttorneyFilter>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryCareerArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCareerConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerFilter>;
};


export type QueryPracticeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPracticeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PracticeFilter>;
};

export type DocumentFilter = {
  attorney?: InputMaybe<AttorneyFilter>;
  blog?: InputMaybe<BlogFilter>;
  career?: InputMaybe<CareerFilter>;
  practice?: InputMaybe<PracticeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Attorney | Blog | Career | Practice | Folder;

export type Attorney = Node & Document & {
  __typename?: 'Attorney';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  photo?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  phone: Scalars['String']['output'];
  education?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  experience?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  practiceAreas?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bio: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AttorneyFilter = {
  name?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  education?: InputMaybe<StringFilter>;
  experience?: InputMaybe<StringFilter>;
  practiceAreas?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
};

export type AttorneyConnectionEdges = {
  __typename?: 'AttorneyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Attorney>;
};

export type AttorneyConnection = Connection & {
  __typename?: 'AttorneyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AttorneyConnectionEdges>>>;
};

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  author: Scalars['String']['output'];
  authorSlug: Scalars['String']['output'];
  date: Scalars['String']['output'];
  category: Scalars['String']['output'];
  readTime?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  authorSlug?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type Career = Node & Document & {
  __typename?: 'Career';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  location: Scalars['String']['output'];
  type: Scalars['String']['output'];
  department: Scalars['String']['output'];
  experience: Scalars['String']['output'];
  description: Scalars['String']['output'];
  responsibilities?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  requirements?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  benefits?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  postedDate?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CareerFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  department?: InputMaybe<StringFilter>;
  experience?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  responsibilities?: InputMaybe<StringFilter>;
  requirements?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<StringFilter>;
  postedDate?: InputMaybe<DatetimeFilter>;
};

export type CareerConnectionEdges = {
  __typename?: 'CareerConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Career>;
};

export type CareerConnection = Connection & {
  __typename?: 'CareerConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CareerConnectionEdges>>>;
};

export type PracticeFaqs = {
  __typename?: 'PracticeFaqs';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type Practice = Node & Document & {
  __typename?: 'Practice';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  shortDescription: Scalars['String']['output'];
  description: Scalars['String']['output'];
  services?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  faqs?: Maybe<Array<Maybe<PracticeFaqs>>>;
  relatedAttorneys?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PracticeFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type PracticeFilter = {
  name?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  shortDescription?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<PracticeFaqsFilter>;
  relatedAttorneys?: InputMaybe<StringFilter>;
};

export type PracticeConnectionEdges = {
  __typename?: 'PracticeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Practice>;
};

export type PracticeConnection = Connection & {
  __typename?: 'PracticeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PracticeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAttorney: Attorney;
  createAttorney: Attorney;
  updateBlog: Blog;
  createBlog: Blog;
  updateCareer: Career;
  createCareer: Career;
  updatePractice: Practice;
  createPractice: Practice;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAttorneyArgs = {
  relativePath: Scalars['String']['input'];
  params: AttorneyMutation;
};


export type MutationCreateAttorneyArgs = {
  relativePath: Scalars['String']['input'];
  params: AttorneyMutation;
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateCareerArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerMutation;
};


export type MutationCreateCareerArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerMutation;
};


export type MutationUpdatePracticeArgs = {
  relativePath: Scalars['String']['input'];
  params: PracticeMutation;
};


export type MutationCreatePracticeArgs = {
  relativePath: Scalars['String']['input'];
  params: PracticeMutation;
};

export type DocumentUpdateMutation = {
  attorney?: InputMaybe<AttorneyMutation>;
  blog?: InputMaybe<BlogMutation>;
  career?: InputMaybe<CareerMutation>;
  practice?: InputMaybe<PracticeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  attorney?: InputMaybe<AttorneyMutation>;
  blog?: InputMaybe<BlogMutation>;
  career?: InputMaybe<CareerMutation>;
  practice?: InputMaybe<PracticeMutation>;
};

export type AttorneyMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  education?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  experience?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  practiceAreas?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bio?: InputMaybe<Scalars['String']['input']>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  authorSlug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type CareerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  department?: InputMaybe<Scalars['String']['input']>;
  experience?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  responsibilities?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  requirements?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  benefits?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  postedDate?: InputMaybe<Scalars['String']['input']>;
};

export type PracticeFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type PracticeMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  shortDescription?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  faqs?: InputMaybe<Array<InputMaybe<PracticeFaqsMutation>>>;
  relatedAttorneys?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AttorneyPartsFragment = { __typename: 'Attorney', name: string, slug: string, title: string, photo?: string | null, email: string, phone: string, education?: Array<string | null> | null, experience?: Array<string | null> | null, practiceAreas?: Array<string | null> | null, bio: string };

export type BlogPartsFragment = { __typename: 'Blog', title: string, slug: string, excerpt: string, author: string, authorSlug: string, date: string, category: string, readTime?: string | null, image?: string | null, body?: any | null };

export type CareerPartsFragment = { __typename: 'Career', title: string, slug: string, location: string, type: string, department: string, experience: string, description: string, responsibilities?: Array<string | null> | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, postedDate?: string | null };

export type PracticePartsFragment = { __typename: 'Practice', name: string, slug: string, icon: string, shortDescription: string, description: string, services?: Array<string | null> | null, relatedAttorneys?: Array<string | null> | null, faqs?: Array<{ __typename: 'PracticeFaqs', question: string, answer: string } | null> | null };

export type AttorneyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AttorneyQuery = { __typename?: 'Query', attorney: { __typename: 'Attorney', id: string, name: string, slug: string, title: string, photo?: string | null, email: string, phone: string, education?: Array<string | null> | null, experience?: Array<string | null> | null, practiceAreas?: Array<string | null> | null, bio: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AttorneyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AttorneyFilter>;
}>;


export type AttorneyConnectionQuery = { __typename?: 'Query', attorneyConnection: { __typename?: 'AttorneyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AttorneyConnectionEdges', cursor: string, node?: { __typename: 'Attorney', id: string, name: string, slug: string, title: string, photo?: string | null, email: string, phone: string, education?: Array<string | null> | null, experience?: Array<string | null> | null, practiceAreas?: Array<string | null> | null, bio: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, slug: string, excerpt: string, author: string, authorSlug: string, date: string, category: string, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, slug: string, excerpt: string, author: string, authorSlug: string, date: string, category: string, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type CareerQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CareerQuery = { __typename?: 'Query', career: { __typename: 'Career', id: string, title: string, slug: string, location: string, type: string, department: string, experience: string, description: string, responsibilities?: Array<string | null> | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, postedDate?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CareerConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerFilter>;
}>;


export type CareerConnectionQuery = { __typename?: 'Query', careerConnection: { __typename?: 'CareerConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CareerConnectionEdges', cursor: string, node?: { __typename: 'Career', id: string, title: string, slug: string, location: string, type: string, department: string, experience: string, description: string, responsibilities?: Array<string | null> | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, postedDate?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PracticeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PracticeQuery = { __typename?: 'Query', practice: { __typename: 'Practice', id: string, name: string, slug: string, icon: string, shortDescription: string, description: string, services?: Array<string | null> | null, relatedAttorneys?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'PracticeFaqs', question: string, answer: string } | null> | null } };

export type PracticeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PracticeFilter>;
}>;


export type PracticeConnectionQuery = { __typename?: 'Query', practiceConnection: { __typename?: 'PracticeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PracticeConnectionEdges', cursor: string, node?: { __typename: 'Practice', id: string, name: string, slug: string, icon: string, shortDescription: string, description: string, services?: Array<string | null> | null, relatedAttorneys?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'PracticeFaqs', question: string, answer: string } | null> | null } | null } | null> | null } };

export const AttorneyPartsFragmentDoc = gql`
    fragment AttorneyParts on Attorney {
  __typename
  name
  slug
  title
  photo
  email
  phone
  education
  experience
  practiceAreas
  bio
}
    `;
export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  slug
  excerpt
  author
  authorSlug
  date
  category
  readTime
  image
  body
}
    `;
export const CareerPartsFragmentDoc = gql`
    fragment CareerParts on Career {
  __typename
  title
  slug
  location
  type
  department
  experience
  description
  responsibilities
  requirements
  benefits
  postedDate
}
    `;
export const PracticePartsFragmentDoc = gql`
    fragment PracticeParts on Practice {
  __typename
  name
  slug
  icon
  shortDescription
  description
  services
  faqs {
    __typename
    question
    answer
  }
  relatedAttorneys
}
    `;
export const AttorneyDocument = gql`
    query attorney($relativePath: String!) {
  attorney(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AttorneyParts
  }
}
    ${AttorneyPartsFragmentDoc}`;
export const AttorneyConnectionDocument = gql`
    query attorneyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AttorneyFilter) {
  attorneyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AttorneyParts
      }
    }
  }
}
    ${AttorneyPartsFragmentDoc}`;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const CareerDocument = gql`
    query career($relativePath: String!) {
  career(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CareerParts
  }
}
    ${CareerPartsFragmentDoc}`;
export const CareerConnectionDocument = gql`
    query careerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CareerFilter) {
  careerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CareerParts
      }
    }
  }
}
    ${CareerPartsFragmentDoc}`;
export const PracticeDocument = gql`
    query practice($relativePath: String!) {
  practice(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PracticeParts
  }
}
    ${PracticePartsFragmentDoc}`;
export const PracticeConnectionDocument = gql`
    query practiceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PracticeFilter) {
  practiceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PracticeParts
      }
    }
  }
}
    ${PracticePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      attorney(variables: AttorneyQueryVariables, options?: C): Promise<{data: AttorneyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AttorneyQueryVariables, query: string}> {
        return requester<{data: AttorneyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AttorneyQueryVariables, query: string}, AttorneyQueryVariables>(AttorneyDocument, variables, options);
      },
    attorneyConnection(variables?: AttorneyConnectionQueryVariables, options?: C): Promise<{data: AttorneyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AttorneyConnectionQueryVariables, query: string}> {
        return requester<{data: AttorneyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AttorneyConnectionQueryVariables, query: string}, AttorneyConnectionQueryVariables>(AttorneyConnectionDocument, variables, options);
      },
    blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    career(variables: CareerQueryVariables, options?: C): Promise<{data: CareerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerQueryVariables, query: string}> {
        return requester<{data: CareerQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerQueryVariables, query: string}, CareerQueryVariables>(CareerDocument, variables, options);
      },
    careerConnection(variables?: CareerConnectionQueryVariables, options?: C): Promise<{data: CareerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerConnectionQueryVariables, query: string}> {
        return requester<{data: CareerConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerConnectionQueryVariables, query: string}, CareerConnectionQueryVariables>(CareerConnectionDocument, variables, options);
      },
    practice(variables: PracticeQueryVariables, options?: C): Promise<{data: PracticeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeQueryVariables, query: string}> {
        return requester<{data: PracticeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeQueryVariables, query: string}, PracticeQueryVariables>(PracticeDocument, variables, options);
      },
    practiceConnection(variables?: PracticeConnectionQueryVariables, options?: C): Promise<{data: PracticeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeConnectionQueryVariables, query: string}> {
        return requester<{data: PracticeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PracticeConnectionQueryVariables, query: string}, PracticeConnectionQueryVariables>(PracticeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  